version: '3.2'

services:
  concourse-keys:
    build: .
    volumes:
      - type: volume
        source: keys-web
        target: /keys/web
        volume:
          nocopy: false
      - type: volume
        source: keys-worker
        target: /keys/worker
        volume:
          nocopy: false

  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbm3in!}
      PGDATA: /database
    volumes:
      - concourse-db:/database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["9080:8080"]
    volumes: ["keys-web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASIC_AUTH_PASSWORD:-flym3in!}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL:-localhost}
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbm3in!}
      CONCOURSE_POSTGRES_DATABASE: concourse
    dns:
      - 8.8.8.8
      - 8.8.4.4

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["keys-worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  concourse-db:
  keys-worker:
  keys-web:
